export const programmingLanguages = [
    { "label": "JavaScript", "value": "javascript" },
    { "label": "Python", "value": "python" },
    { "label": "Java", "value": "java" },
    { "label": "C++", "value": "cpp" },
    { "label": "C#", "value": "csharp" },
    { "label": "Ruby", "value": "ruby" },
    { "label": "Swift", "value": "swift" },
    { "label": "Go", "value": "go" },
    { "label": "Kotlin", "value": "kotlin" },
    { "label": "Rust", "value": "rust" },
    { "label": "TypeScript", "value": "typescript" },
    { "label": "PHP", "value": "php" },
    { "label": "HTML", "value": "html" },
    { "label": "CSS", "value": "css" },
    { "label": "SQL", "value": "sql" },
    { "label": "Shell", "value": "shell" },
    { "label": "C", "value": "c" },
    { "label": "Perl", "value": "perl" },
    { "label": "Scala", "value": "scala" },
    { "label": "Haskell", "value": "haskell" },
    { "label": "Lua", "value": "lua" },
    { "label": "R", "value": "r" },
    { "label": "Dart", "value": "dart" },
    { "label": "Objective-C", "value": "objective-c" }
]
